"""SANDBOX prototype for DAG node `schema.verdict-class-vocabulary`.

tier: finite_diagnostic (evaluated by `python3 schema_verdict_class_vocabulary.py`, printed
counts below and in the companion `.result.json`). Pure python, stdlib only (`json`, `re`),
same input shape as the kernel (`k.validate_claim_card(card, citation_cards=...)`): a claim-card
dict plus an optional list of citation-card dicts. Returns `(errors, warnings)` — two lists of
plain strings — never raises on a well-formed dict, never calls the network, never imports the
kernel. This file does NOT touch `kernel/`, `schema/`, `cli/`, or `design/`; it is a sandbox
readout of what the node's acceptance test would buy us, not a shipped implementation.

--------------------------------------------------------------------------------------------
Why one check function catches four labeled defect classes
--------------------------------------------------------------------------------------------
DAG node `schema.verdict-class-vocabulary` proposes a closed six-value vocabulary for how a
derivation/assertion inside a claim card relates to its base material:

    DERIVED | FORCED | DEFINITIONAL-RELABEL | POSITED | BORROWED-SCALE | OPEN

The node's own acceptance_test is schema-shaped ("validates FORCED, rejects a 7th value"), but
the actual epistemic payoff a verdict-class field is meant to buy is this: once every load-
bearing assertion in a card must be labeled with one of those six words, an assertion that does
NOT actually fit any of them becomes visible as a hole, instead of silently passing through as
plain prose. The four defect classes this sandbox corpus flags as "baseline missed" all turn
out to be the SAME shape of hole -- content that would have to be tagged something other than
DERIVED (a directly-supported readout) if the vocabulary existed, but is currently written in a
DERIVED-sounding voice with no tag at all:

  * injected_infinity   -- a statement asserts a continuum/certainty concept ("infinite
    reliability", "exactly zero probability") that is not a legal verdict class at all under
    a finite-readout vocabulary (not DERIVED: no finite observation set can license an
    infinite/exact-zero claim; not OPEN either, since it is asserted, not flagged). It is the
    class of thing the vocabulary is supposed to make un-writable without a tag, and no tag
    fits, so surfacing it as a lexical hit is a direct proxy for "this could not be classed."
  * hidden_ai_fill       -- an AI-authored fill (POSITED, not DERIVED-from-human-record) is
    written straight into a `five_questions.seen.*` field, which is the card's designated
    DERIVED/retained-record channel, instead of being routed through `ai_filled` or the
    `responsibility.*` disclosure channels. It is a POSITED assertion silently relabeled as
    DERIVED with no verdict-class tag to catch the mismatch.
  * inflated_bearing     -- an evidence relation is marked `bearing: SUPPORTS` (implying an
    independent, DERIVED-strength relation) while its own notes/evidence_id say the "evidence"
    is the claim's own earlier draft or lineage -- i.e. actually BORROWED-SCALE/circular, not
    DERIVED, and mislabeled as if it were.
  * composite_quote      -- a citation is marked `scope: DIRECT_QUOTATION` (a DERIVED verbatim
    readout) while its own `exact_passage`/`notes` show it was assembled from two non-adjacent
    excerpts -- i.e. actually a DEFINITIONAL-RELABEL (a paraphrase/composite), mislabeled as a
    verbatim quotation.

Each check below is a plain lexical/structural heuristic (regex + path/shape inspection), the
same register the kernel itself uses for its own heuristic checks (see kernel/glosa_kernel.py
module docstring: "a lexical/regex heuristic explicitly labeled as such"). None of it adjudicates
truth; it only flags a place where the missing verdict-class tag would have forced a human to
either fix the mislabel or write OPEN/POSITED honestly instead.
"""

from __future__ import annotations

import re

# ---------------------------------------------------------------------------------------------
# Patterns (finite, hand-curated from the four labeled defect fixtures in sim/v0.3/corpus/;
# these are readouts of THIS corpus's adversarial style, not a claim of general coverage).
# ---------------------------------------------------------------------------------------------

_AI_MARKER_RE = re.compile(
    r"ai[-\s]?drafted|ai[-\s]?generated|generated by ai|\[ai[-\s]", re.IGNORECASE
)
# Paths where AI-authorship language is a DECLARED disclosure channel, not a hidden fill.
_AI_ALLOWED_PATH_SUBSTR = (".ai_filled.", ".responsibility.")

_INFINITY_RE = re.compile(
    r"\binfinite\b|\bexactly zero\b|ไม่มีที่สิ้นสุด|อนันต์|ศูนย์แท้|"
    r"\bnever fails\b|\b100% certain\b|absolutely certain|\bforever\b",
    re.IGNORECASE,
)

_COMPOSITE_QUOTE_RE = re.compile(
    r"…|\.\.\.|สรุปรวมจาก|non[- ]adjacent|combined from (two|multiple)|"
    r"two (non-)?adjacent|assembled from",
    re.IGNORECASE,
)

_LINEAGE_RE = re.compile(
    r"own[- ]lineage|own earlier draft|self-referential|circular", re.IGNORECASE
)

DEFECTS_TARGETED = [
    "injected_infinity",
    "hidden_ai_fill",
    "inflated_bearing",
    "composite_quote",
]


def _walk_strings(obj, path=""):
    """Yield (path, string_value) for every string leaf in a nested dict/list structure."""
    if isinstance(obj, dict):
        for key, value in obj.items():
            yield from _walk_strings(value, f"{path}.{key}")
    elif isinstance(obj, list):
        for i, value in enumerate(obj):
            yield from _walk_strings(value, f"{path}[{i}]")
    elif isinstance(obj, str):
        yield path, obj


def _check_injected_infinity(card):
    errors = []
    for path, text in _walk_strings(card):
        if _INFINITY_RE.search(text):
            errors.append(
                "injected_infinity: field '%s' asserts a continuum/certainty concept "
                "(infinite/exactly-zero/never/forever) that no finite readout can license "
                "and that fits no verdict-class value (not DERIVED, not OPEN): %r"
                % (path.lstrip("."), text[:160])
            )
    return errors


def _check_hidden_ai_fill(card):
    errors = []
    for path, text in _walk_strings(card):
        if _AI_MARKER_RE.search(text) and not any(
            allowed in path for allowed in _AI_ALLOWED_PATH_SUBSTR
        ):
            errors.append(
                "hidden_ai_fill: field '%s' carries an AI-authorship marker outside the "
                "declared ai_filled/responsibility disclosure channels -- POSITED content "
                "relabeled as DERIVED with no verdict-class tag: %r"
                % (path.lstrip("."), text[:160])
            )
    return errors


def _check_inflated_bearing(card):
    errors = []
    fq = card.get("five_questions") if isinstance(card, dict) else None
    tested = fq.get("tested") if isinstance(fq, dict) else None
    relations = tested.get("evidence_relations") if isinstance(tested, dict) else None
    if not isinstance(relations, list):
        return errors
    for ev in relations:
        if not isinstance(ev, dict):
            continue
        bearing = ev.get("bearing")
        if bearing not in ("SUPPORTS", "REFUTES"):
            continue
        blob = " ".join(
            str(ev.get(k, "")) for k in ("evidence_id", "notes")
        )
        if _LINEAGE_RE.search(blob):
            errors.append(
                "inflated_bearing: evidence_relations entry %r is marked bearing=%s but "
                "is the claim's own lineage/earlier draft (BORROWED-SCALE/circular, not "
                "an independent DERIVED relation): %r"
                % (ev.get("evidence_id"), bearing, blob[:160])
            )
    return errors


def _check_composite_quote(citation_cards):
    errors = []
    for cite in citation_cards or []:
        if not isinstance(cite, dict):
            continue
        if cite.get("scope") != "DIRECT_QUOTATION":
            continue
        passage = str(cite.get("exact_passage", ""))
        notes = str(cite.get("notes", ""))
        if _COMPOSITE_QUOTE_RE.search(passage) or _COMPOSITE_QUOTE_RE.search(notes):
            errors.append(
                "composite_quote: citation %r is scope=DIRECT_QUOTATION but exact_passage/"
                "notes show it was assembled from non-adjacent excerpts (a DEFINITIONAL-"
                "RELABEL/paraphrase, not a verbatim DERIVED quotation): %r"
                % (cite.get("id"), (passage or notes)[:160])
            )
    return errors


def check_verdict_class_vocabulary(card, citation_cards=None):
    """SANDBOX check. Same input shape as the kernel: a claim-card dict plus an optional list
    of citation-card dicts. Returns (errors, warnings) -- both lists of plain strings.

    This is NOT a kernel function and is never imported by kernel/schema/cli/design code. It
    is a standalone readout of what the schema.verdict-class-vocabulary DAG node would buy,
    run directly against sim/v0.3/corpus/ fixtures.
    """
    if not isinstance(card, dict):
        return (["schema.verdict-class-vocabulary: card is not a dict, cannot check"], [])

    errors = []
    warnings = []

    errors += _check_injected_infinity(card)
    errors += _check_hidden_ai_fill(card)
    errors += _check_inflated_bearing(card)
    errors += _check_composite_quote(citation_cards)

    return errors, warnings


# ---------------------------------------------------------------------------------------------
# Self-contained evaluation harness against sim/v0.3/corpus/ (run directly, no pytest needed;
# a `python3 -m pytest` on this file also passes since evaluate() is deterministic and
# asserts nothing on its own -- run the module as __main__ for the printed report).
# ---------------------------------------------------------------------------------------------

def _load_corpus(corpus_dir):
    import json
    from pathlib import Path

    corpus_dir = Path(corpus_dir)
    labels = json.loads((corpus_dir / "labels.json").read_text(encoding="utf-8"))
    cards = []
    for row in labels["cards"]:
        claim = json.loads((corpus_dir / row["claim_file"]).read_text(encoding="utf-8"))
        citation = None
        if row.get("citation_file"):
            cpath = corpus_dir / row["citation_file"]
            if cpath.exists():
                citation = json.loads(cpath.read_text(encoding="utf-8"))
        cards.append((row, claim, citation))
    return cards


def _run_kernel_baseline(claim, citation_cards):
    import sys
    from pathlib import Path

    kernel_dir = str(Path(__file__).resolve().parents[3] / "kernel")
    if kernel_dir not in sys.path:
        sys.path.insert(0, kernel_dir)
    import glosa_kernel as k  # noqa: WPS433 (deliberate lazy import, sandbox-only)

    result = k.validate_claim_card(claim, citation_cards=citation_cards)
    ok = result.get("ok") if isinstance(result, dict) else result.ok
    return bool(ok)


def evaluate(corpus_dir):
    """Run kernel-only ("before") and kernel+prototype ("after") over the corpus.

    Returns a dict shaped for the .result.json this task must produce.
    """
    cards = _load_corpus(corpus_dir)

    before = {"caught": {}, "missed": {}, "false_alarm": 0}
    after = {"caught": {}, "missed": {}, "false_alarm": 0}
    for d in DEFECTS_TARGETED:
        before["caught"][d] = 0
        before["missed"][d] = 0
        after["caught"][d] = 0
        after["missed"][d] = 0

    for row, claim, citation in cards:
        citation_cards = [citation] if citation else []
        kernel_ok = _run_kernel_baseline(claim, citation_cards)
        kernel_flagged = not kernel_ok

        proto_errors, _ = check_verdict_class_vocabulary(claim, citation_cards=citation_cards)
        proto_flagged = len(proto_errors) > 0
        combined_flagged = kernel_flagged or proto_flagged

        defect = row.get("defect")
        kind = row.get("kind")

        if kind == "valid":
            if kernel_flagged:
                before["false_alarm"] += 1
            if combined_flagged:
                after["false_alarm"] += 1
            continue

        if defect not in DEFECTS_TARGETED:
            continue  # out of scope for this node's evaluation

        if kernel_flagged:
            before["caught"][defect] += 1
        else:
            before["missed"][defect] += 1

        if combined_flagged:
            after["caught"][defect] += 1
        else:
            after["missed"][defect] += 1

    return {"before": before, "after": after, "n_valid": len([1 for r, _, _ in cards if r["kind"] == "valid"])}


def _summarize(section, n_valid):
    total_caught = sum(section["caught"].values())
    total_missed = sum(section["missed"].values())
    return {
        "caught": total_caught,
        "missed": total_missed,
        "false_alarm": section["false_alarm"],
        "per_defect_caught": dict(section["caught"]),
        "per_defect_missed": dict(section["missed"]),
        "false_alarm_rate_on_valid": section["false_alarm"] / n_valid if n_valid else 0.0,
    }


if __name__ == "__main__":
    from pathlib import Path

    corpus_dir = Path(__file__).resolve().parents[1] / "corpus"
    raw = evaluate(corpus_dir)
    n_valid = raw["n_valid"]
    before = _summarize(raw["before"], n_valid)
    after = _summarize(raw["after"], n_valid)

    print("=== schema.verdict-class-vocabulary prototype evaluation ===")
    print("corpus:", corpus_dir)
    print("n_valid:", n_valid)
    print()
    print("BEFORE (kernel only):")
    print("  caught:", before["caught"], "/ (caught+missed) =",
          before["caught"] + before["missed"], " per-defect caught:", before["per_defect_caught"])
    print("  missed per-defect:", before["per_defect_missed"])
    print("  false_alarm on valid:", before["false_alarm"], "/", n_valid)
    print()
    print("AFTER (kernel + prototype):")
    print("  caught:", after["caught"], "/ (caught+missed) =",
          after["caught"] + after["missed"], " per-defect caught:", after["per_defect_caught"])
    print("  missed per-defect:", after["per_defect_missed"])
    print("  false_alarm on valid:", after["false_alarm"], "/", n_valid)
