"""Sim-corpus regression test — REPO_SPEC_v0.6_PATCH.md §1 / §5.

Runs the CURRENT kernel (kernel/glosa_kernel.py, unmodified by this file) over the
180-card fixed corpus at tests/sim/corpus/ and asserts it does not regress below the
last-recorded baseline in tests/sim/baseline.json:

  (a) loads the existing corpus (tests/sim/corpus/, generated by tests/sim/gen_corpus.py —
      not regenerated here since the corpus is a tracked, printed fixture; regeneration is
      a separate, explicit action, not an implicit side effect of every test run)
  (b) recall on the current kernel run >= the recall recorded in tests/sim/baseline.json,
      and false alarms == 0 on the 60 valid cards
  (c) skipped gracefully (not failed) if the kernel import fails

Tier of every number this test compares: finite_diagnostic — an exact tally over this one
fixed, printed 180-card synthetic corpus, this run. Not a general kernel-quality claim
(one-fact-one-home: the corpus/labels/methodology narrative lives in tests/sim/report.md and
tests/sim/baseline.py; this file only re-runs the same counting logic against the CURRENT
kernel and compares to the recorded baseline — it does not re-derive or restate that
narrative).

This file never writes to tests/sim/baseline.json — it reuses tests/sim/baseline.py's own
run_card()/defect_caught() functions (imported, not reimplemented) purely as pure functions,
and never calls that module's main() (which would overwrite the recorded baseline with the
current run, destroying the "last-recorded" comparison point this test exists to check
against).
"""
import importlib.util
import json
import sys
from pathlib import Path

import pytest

HERE = Path(__file__).resolve().parent
SIM_DIR = HERE / "sim"
CORPUS_DIR = SIM_DIR / "corpus"
BASELINE_JSON = SIM_DIR / "baseline.json"
REPO = HERE.parent

try:
    sys.path.insert(0, str(REPO / "kernel"))
    import glosa_kernel as kernel  # noqa: E402
    KERNEL_IMPORT_ERROR = None
except Exception as exc:  # pragma: no cover - environment-dependent
    kernel = None
    KERNEL_IMPORT_ERROR = exc


def _load_baseline_module():
    """Import tests/sim/baseline.py as a module, for its pure run_card()/defect_caught()
    helpers only. Does NOT call baseline.main() (that writes tests/sim/baseline.json)."""
    spec = importlib.util.spec_from_file_location("_sim_baseline_regression", SIM_DIR / "baseline.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


@pytest.mark.skipif(kernel is None, reason=f"kernel import failed: {KERNEL_IMPORT_ERROR}")
def test_sim_corpus_recall_and_false_alarms_do_not_regress():
    assert BASELINE_JSON.exists(), "tests/sim/baseline.json (recorded baseline) is missing"
    baseline = json.loads(BASELINE_JSON.read_text(encoding="utf-8"))
    baseline_recall = baseline["recall"]

    labels_path = CORPUS_DIR / "labels.json"
    assert labels_path.exists(), "tests/sim/corpus/labels.json (fixed corpus) is missing"
    labels = json.loads(labels_path.read_text(encoding="utf-8"))
    cards = labels["cards"]
    assert len(cards) == baseline["corpus"]["n_total"], (
        "tests/sim/corpus/labels.json card count no longer matches the recorded baseline's "
        "corpus size — the fixed corpus this test compares against has changed shape"
    )

    baseline_mod = _load_baseline_module()

    total_adv = 0
    total_caught = 0
    valid_n = 0
    valid_false_alarm = 0
    valid_false_alarm_ids = []

    for entry in cards:
        card = json.loads((CORPUS_DIR / entry["claim_file"]).read_text(encoding="utf-8"))
        citation = json.loads((CORPUS_DIR / entry["citation_file"]).read_text(encoding="utf-8"))
        claim_res = kernel.validate_claim_card(card, citation_cards=[citation])
        citation_res = kernel.validate_citation_card(citation)
        all_msgs = list(claim_res.get("errors") or []) + list(claim_res.get("warnings") or []) \
            + list(citation_res.get("errors") or []) + list(citation_res.get("warnings") or [])
        computed_disclaimers = {d["id"] for d in kernel.compute_disclaimers(card)}
        declared_disclaimers = {d.get("id") for d in (card.get("disclaimers_emitted") or [])}
        result = {
            "claim_ok": claim_res.get("ok"),
            "citation_ok": citation_res.get("ok"),
            "messages": all_msgs,
            "disclaimer_gap": sorted(computed_disclaimers - declared_disclaimers),
        }

        if entry["kind"] == "valid":
            valid_n += 1
            if not result["claim_ok"] or not result["citation_ok"]:
                valid_false_alarm += 1
                valid_false_alarm_ids.append(entry["id"])
        else:
            total_adv += 1
            if baseline_mod.defect_caught(entry["defect"], result):
                total_caught += 1

    recall = total_caught / total_adv if total_adv else 0.0

    assert valid_false_alarm == 0, (
        f"false alarms on valid corpus cards: {valid_false_alarm_ids} "
        f"(baseline recorded 0/{baseline['valid']['n']})"
    )
    assert recall >= baseline_recall, (
        f"current kernel recall {recall:.4f} on tests/sim/corpus/ regressed below the "
        f"recorded baseline recall {baseline_recall:.4f} in tests/sim/baseline.json"
    )


# =============================================================================================
# v0.4 — design/SESSION_ARCH_v0.4_SPEC.md §5's five session-architecture defect classes, over
# tests/sim/corpus/v04/ (see tests/sim/gen_corpus.py's gen_v04_corpus()).
#
# TODO(schema.retention-direction-field, SA-1, kernel.reciprocal-lineage-diagnostic, SA-3): the
# schema/kernel fields these fixtures target (hypothesis_selection.yaml `retained_direction` /
# `chooser_reaffirmations[]`, blackbox_note.schema.json `ai_state_at_boundary`, a session-level
# question-drift/momentum check) do not exist in schema/*.json or kernel/glosa_kernel.py yet
# (confirmed by direct grep, 2026-09-05) — those are separate, still-pending v0.4 proposals. This
# test therefore does NOT (and must not be read to) assert anything about the shipped
# kernel/schema's own behaviour on these fixtures; it asserts that tests/sim/baseline.py's own
# `_check_*_v04` PROTOTYPE reference checkers (tier `Dr`, a hand-written reading of §5's
# failing_control clauses) are internally consistent with what tests/sim/corpus/v04/labels.json
# says each fixture is a control for — i.e. this is a self-consistency test of the sim's own
# prototype, not a kernel regression test. Once the real fields/rules ship, this test (and
# baseline.py's `main_v04`) should be repointed at the real kernel/schema calls and this TODO
# removed.
# =============================================================================================

V04_DIR = CORPUS_DIR / "v04"
V04_LABELS = V04_DIR / "labels.json"


@pytest.mark.skipif(not V04_LABELS.exists(), reason="tests/sim/corpus/v04/labels.json not generated yet")
def test_v04_prototype_checkers_match_fixture_labels():
    baseline_mod = _load_baseline_module()
    labels = json.loads(V04_LABELS.read_text(encoding="utf-8"))
    cards = labels["cards"]
    assert cards, "tests/sim/corpus/v04/labels.json has no fixtures"

    per_defect_adv = {d: 0 for d in labels["defects"]}
    per_defect_valid = {d: 0 for d in labels["defects"]}
    wrong = []

    for entry in cards:
        rel = entry["file"].split("v04/", 1)[1]
        obj = json.loads((V04_DIR / rel).read_text(encoding="utf-8"))
        fname = Path(rel).name
        defect = next((d for d in labels["defects"] if fname.startswith(d + "_")), None)
        assert defect, f"v0.4 fixture {rel!r} filename does not name a known defect class"
        checker = baseline_mod._V04_CHECKERS[defect]
        msg = checker(obj)
        if entry["kind"] == "adversarial":
            per_defect_adv[defect] += 1
            if msg is None:
                wrong.append((defect, entry["id"], "adversarial fixture NOT flagged"))
        else:
            per_defect_valid[defect] += 1
            if msg is not None:
                wrong.append((defect, entry["id"], f"valid control WAS flagged: {msg!r}"))

    for defect in labels["defects"]:
        assert per_defect_adv[defect] >= 6, f"{defect}: fewer than 6 adversarial fixtures"
        assert per_defect_valid[defect] >= 6, f"{defect}: fewer than 6 valid-control fixtures"

    assert not wrong, (
        "v0.4 prototype checker disagreed with its own fixture's declared kind:\n"
        + "\n".join(f"  {d} {cid}: {reason}" for d, cid, reason in wrong)
    )
