"""Sim-corpus regression test — REPO_SPEC_v0.6_PATCH.md §1 / §5.

Runs the CURRENT kernel (kernel/glosa_kernel.py, unmodified by this file) over the
180-card fixed corpus at tests/sim/corpus/ and asserts it does not regress below the
last-recorded baseline in tests/sim/baseline.json:

  (a) loads the existing corpus (tests/sim/corpus/, generated by tests/sim/gen_corpus.py —
      not regenerated here since the corpus is a tracked, printed fixture; regeneration is
      a separate, explicit action, not an implicit side effect of every test run)
  (b) recall on the current kernel run >= the recall recorded in tests/sim/baseline.json,
      and false alarms == 0 on the 60 valid cards
  (c) skipped gracefully (not failed) if the kernel import fails

Tier of every number this test compares: finite_diagnostic — an exact tally over this one
fixed, printed 180-card synthetic corpus, this run. Not a general kernel-quality claim
(one-fact-one-home: the corpus/labels/methodology narrative lives in tests/sim/report.md and
tests/sim/baseline.py; this file only re-runs the same counting logic against the CURRENT
kernel and compares to the recorded baseline — it does not re-derive or restate that
narrative).

This file never writes to tests/sim/baseline.json — it reuses tests/sim/baseline.py's own
run_card()/defect_caught() functions (imported, not reimplemented) purely as pure functions,
and never calls that module's main() (which would overwrite the recorded baseline with the
current run, destroying the "last-recorded" comparison point this test exists to check
against).
"""
import importlib.util
import json
import sys
from pathlib import Path

import pytest

HERE = Path(__file__).resolve().parent
SIM_DIR = HERE / "sim"
CORPUS_DIR = SIM_DIR / "corpus"
BASELINE_JSON = SIM_DIR / "baseline.json"
REPO = HERE.parent

try:
    sys.path.insert(0, str(REPO / "kernel"))
    import glosa_kernel as kernel  # noqa: E402
    KERNEL_IMPORT_ERROR = None
except Exception as exc:  # pragma: no cover - environment-dependent
    kernel = None
    KERNEL_IMPORT_ERROR = exc


def _load_baseline_module():
    """Import tests/sim/baseline.py as a module, for its pure run_card()/defect_caught()
    helpers only. Does NOT call baseline.main() (that writes tests/sim/baseline.json)."""
    spec = importlib.util.spec_from_file_location("_sim_baseline_regression", SIM_DIR / "baseline.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


@pytest.mark.skipif(kernel is None, reason=f"kernel import failed: {KERNEL_IMPORT_ERROR}")
def test_sim_corpus_recall_and_false_alarms_do_not_regress():
    assert BASELINE_JSON.exists(), "tests/sim/baseline.json (recorded baseline) is missing"
    baseline = json.loads(BASELINE_JSON.read_text(encoding="utf-8"))
    baseline_recall = baseline["recall"]

    labels_path = CORPUS_DIR / "labels.json"
    assert labels_path.exists(), "tests/sim/corpus/labels.json (fixed corpus) is missing"
    labels = json.loads(labels_path.read_text(encoding="utf-8"))
    cards = labels["cards"]
    assert len(cards) == baseline["corpus"]["n_total"], (
        "tests/sim/corpus/labels.json card count no longer matches the recorded baseline's "
        "corpus size — the fixed corpus this test compares against has changed shape"
    )

    baseline_mod = _load_baseline_module()

    total_adv = 0
    total_caught = 0
    valid_n = 0
    valid_false_alarm = 0
    valid_false_alarm_ids = []

    for entry in cards:
        card = json.loads((CORPUS_DIR / entry["claim_file"]).read_text(encoding="utf-8"))
        citation = json.loads((CORPUS_DIR / entry["citation_file"]).read_text(encoding="utf-8"))
        claim_res = kernel.validate_claim_card(card, citation_cards=[citation])
        citation_res = kernel.validate_citation_card(citation)
        all_msgs = list(claim_res.get("errors") or []) + list(claim_res.get("warnings") or []) \
            + list(citation_res.get("errors") or []) + list(citation_res.get("warnings") or [])
        computed_disclaimers = {d["id"] for d in kernel.compute_disclaimers(card)}
        declared_disclaimers = {d.get("id") for d in (card.get("disclaimers_emitted") or [])}
        result = {
            "claim_ok": claim_res.get("ok"),
            "citation_ok": citation_res.get("ok"),
            "messages": all_msgs,
            "disclaimer_gap": sorted(computed_disclaimers - declared_disclaimers),
        }

        if entry["kind"] == "valid":
            valid_n += 1
            if not result["claim_ok"] or not result["citation_ok"]:
                valid_false_alarm += 1
                valid_false_alarm_ids.append(entry["id"])
        else:
            total_adv += 1
            if baseline_mod.defect_caught(entry["defect"], result):
                total_caught += 1

    recall = total_caught / total_adv if total_adv else 0.0

    assert valid_false_alarm == 0, (
        f"false alarms on valid corpus cards: {valid_false_alarm_ids} "
        f"(baseline recorded 0/{baseline['valid']['n']})"
    )
    assert recall >= baseline_recall, (
        f"current kernel recall {recall:.4f} on tests/sim/corpus/ regressed below the "
        f"recorded baseline recall {baseline_recall:.4f} in tests/sim/baseline.json"
    )
