#!/usr/bin/env python3
"""
glosa/tools/obsidian_bridge.py — OPTIONAL Obsidian bridge for the glosa repo.

Founder rule, verbatim (2026-09-04): "เชื่อมกับระบบ Obsidian ได้เลย มีก็เชื่อม ไม่มีก็ไม่เชื่อม"
(connect to Obsidian if one exists; if not, do nothing). This tool NEVER fails a build, a
render, or a CI check because a vault is absent — every command below degrades to a clean,
explicit "no vault — bridge skipped" and exit 0 when no vault is configured.

Readout discipline: this bridge renders a VIEW of files that already exist in the repo
(paper/claims/*.yaml, blackbox/*, kg/*.jsonl, records/lit/<hypothesis>/*, registry/, methodology/,
incidents/). It never changes the tier, status, or content of a source file. Every generated note
carries a header saying so and naming the source file to edit instead. A human editing tags/links
directly in Obsidian is captured only via `harvest`, and only as a CANDIDATE file the human must
confirm — this bridge never silently rewrites a source YAML.

Stdlib only. PyYAML is used if imported successfully; otherwise a small best-effort YAML-subset
reader (`_yaml_load`) is used instead (documented limits below). No network calls anywhere.

Commands
--------
    obsidian_bridge.py detect
    obsidian_bridge.py sync [--vault PATH] [--dry-run]
    obsidian_bridge.py check [--vault PATH]
    obsidian_bridge.py harvest [--vault PATH] [--dry-run]
    obsidian_bridge.py unlink [--vault PATH]

Vault resolution order (see `detect()`):
    1. env var GLOSA_OBSIDIAN_VAULT (a path; "none"/"" disables the bridge outright)
    2. ~/.config/glosa/author_profile.json -> defaults.obsidian_vault
    3. "self" mode — the glosa repo's own working tree, treated as a vault at
       <repo>/obsidian/ (Obsidian can open any folder; this is the always-available fallback).
       Self mode can be turned off with GLOSA_OBSIDIAN_DISABLE=1 (then "no vault — bridge skipped").

Never touched by this tool: `.obsidian/` (Obsidian's own app config — appearance, plugins,
workspace layout). This bridge only ever reads/writes inside `<vault>/glosa/`.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from pathlib import Path
from typing import Any

VERSION = "0.1.0"
GENERATED_HEADER = (
    "> generated by glosa obsidian_bridge v{version} — do not edit here; "
    "edit the source file: `{source}`"
)
MANIFEST_NAME = ".glosa_bridge_manifest.json"
LENS_NOTE_TITLE = "Readout Universe — Yaoharee Lahtee"

REPO_ROOT = Path(__file__).resolve().parent.parent

# --------------------------------------------------------------------------
# Minimal YAML-subset reader (used only if PyYAML is not importable)
# --------------------------------------------------------------------------
try:
    import yaml as _pyyaml  # type: ignore

    def _yaml_load(text: str) -> Any:
        return _pyyaml.safe_load(text)

    _YAML_BACKEND = "pyyaml"
except Exception:  # pragma: no cover - exercised on machines without pyyaml
    _YAML_BACKEND = "builtin-subset"

    def _scalar(tok: str) -> Any:
        tok = tok.strip()
        if tok == "" :
            return None
        if tok in ("null", "~", "Null", "NULL"):
            return None
        if tok in ("true", "True", "TRUE"):
            return True
        if tok in ("false", "False", "FALSE"):
            return False
        if len(tok) >= 2 and tok[0] == tok[-1] and tok[0] in ("'", '"'):
            return tok[1:-1]
        if tok == "[]":
            return []
        if tok == "{}":
            return {}
        if tok.startswith("[") and tok.endswith("]"):
            inner = tok[1:-1].strip()
            if not inner:
                return []
            return [_scalar(p) for p in _split_flow(inner)]
        try:
            if re.fullmatch(r"[+-]?\d+", tok):
                return int(tok)
            if re.fullmatch(r"[+-]?\d*\.\d+", tok):
                return float(tok)
        except Exception:
            pass
        return tok

    def _split_flow(inner: str) -> list[str]:
        parts, depth, cur = [], 0, ""
        for ch in inner:
            if ch in "[{":
                depth += 1
            elif ch in "]}":
                depth -= 1
            if ch == "," and depth == 0:
                parts.append(cur)
                cur = ""
            else:
                cur += ch
        if cur.strip():
            parts.append(cur)
        return parts

    def _strip_full_line_comment(line: str) -> str:
        # Only strips a comment that starts a line after optional whitespace, or is clearly
        # preceded by whitespace and not inside a quote. Good enough for the clean, comment-light
        # instance files this bridge actually parses (templates, which are comment-heavy, are
        # never parsed as data by this tool — only referenced for field names in code/docs).
        if re.match(r"^\s*#", line):
            return ""
        m = re.search(r"\s+#(?![^'\"]*['\"]\s*$)", line)
        return line

    def _yaml_load(text: str) -> Any:
        lines = [l.rstrip("\n") for l in text.split("\n")]
        clean: list[tuple[int, str]] = []
        for raw in lines:
            if re.match(r"^\s*#", raw) or not raw.strip():
                continue
            indent = len(raw) - len(raw.lstrip(" "))
            clean.append((indent, raw.strip()))

        pos = [0]

        def parse_block(min_indent: int) -> Any:
            if pos[0] >= len(clean):
                return None
            indent, content = clean[pos[0]]
            if indent < min_indent:
                return None
            if content.startswith("- "):
                items = []
                base_indent = indent
                while pos[0] < len(clean) and clean[pos[0]][0] == base_indent and clean[pos[0]][1].startswith("- "):
                    _, c = clean[pos[0]]
                    rest = c[2:]
                    pos[0] += 1
                    if ":" in rest and not rest.strip().startswith(("'", '"')):
                        key, _, val = rest.partition(":")
                        sub = {}
                        val = val.strip()
                        if val == "":
                            nxt = parse_block(base_indent + 1)
                            sub[key.strip()] = nxt
                        else:
                            sub[key.strip()] = _scalar(val)
                        while pos[0] < len(clean) and clean[pos[0]][0] > base_indent:
                            k2, c2 = clean[pos[0]]
                            if c2.startswith("- "):
                                break
                            key2, _, val2 = c2.partition(":")
                            pos[0] += 1
                            val2 = val2.strip()
                            if val2 == "":
                                sub[key2.strip()] = parse_block(k2 + 1)
                            else:
                                sub[key2.strip()] = _scalar(val2)
                        items.append(sub)
                    else:
                        items.append(_scalar(rest))
                return items
            else:
                mapping: dict[str, Any] = {}
                base_indent = indent
                while pos[0] < len(clean) and clean[pos[0]][0] == base_indent:
                    _, c = clean[pos[0]]
                    if c.startswith("- "):
                        break
                    key, sep, val = c.partition(":")
                    if not sep:
                        pos[0] += 1
                        continue
                    pos[0] += 1
                    val = val.strip()
                    if val in ("|", ">"):
                        block_lines = []
                        while pos[0] < len(clean) and clean[pos[0]][0] > base_indent:
                            block_lines.append(clean[pos[0]][1])
                            pos[0] += 1
                        mapping[key.strip()] = "\n".join(block_lines) if val == "|" else " ".join(block_lines)
                    elif val == "":
                        if pos[0] < len(clean) and clean[pos[0]][0] > base_indent:
                            mapping[key.strip()] = parse_block(base_indent + 1)
                        else:
                            mapping[key.strip()] = None
                    else:
                        # Plain multi-line scalar continuation: YAML folds a bare (unquoted,
                        # non "|"/">"）scalar's following, more-indented lines into the same
                        # value (space-joined) as long as they don't look like a new mapping
                        # key or a list item — this is common in this repo's hand-written YAML
                        # (long statement/description text wrapped across lines with no `|`).
                        pieces = [val] if not (val.startswith(("'", '"'))) else None
                        scalar_val = _scalar(val)
                        if pieces is not None and isinstance(scalar_val, str):
                            while pos[0] < len(clean) and clean[pos[0]][0] > base_indent:
                                cont = clean[pos[0]][1]
                                if cont.startswith("- ") or re.match(r"^[\w.\-]+:( |$)", cont):
                                    break
                                pieces.append(cont)
                                pos[0] += 1
                            scalar_val = " ".join(pieces)
                        mapping[key.strip()] = scalar_val
                return mapping

        return parse_block(0)


def load_yaml_file(path: Path) -> Any:
    try:
        return _yaml_load(path.read_text(encoding="utf-8"))
    except Exception as exc:
        return {"_parse_error": str(exc), "_path": str(path)}


# --------------------------------------------------------------------------
# Vault detection
# --------------------------------------------------------------------------
class VaultInfo:
    def __init__(self, mode: str, path: Path | None, reason: str):
        self.mode = mode  # "env" | "profile" | "self" | "none"
        self.path = path
        self.reason = reason

    def __repr__(self) -> str:
        return f"VaultInfo(mode={self.mode!r}, path={self.path}, reason={self.reason!r})"


def _author_profile_vault() -> Path | None:
    profile_path = Path(os.path.expanduser("~/.config/glosa/author_profile.json"))
    if not profile_path.exists():
        return None
    try:
        data = json.loads(profile_path.read_text(encoding="utf-8"))
    except Exception:
        return None
    val = (data.get("defaults") or {}).get("obsidian_vault")
    if not val:
        return None
    return Path(os.path.expanduser(str(val)))


def detect() -> VaultInfo:
    """Vault resolution order: env -> author_profile -> self. Never raises."""
    if os.environ.get("GLOSA_OBSIDIAN_DISABLE") == "1":
        return VaultInfo("none", None, "GLOSA_OBSIDIAN_DISABLE=1 set — bridge explicitly disabled")

    env_val = os.environ.get("GLOSA_OBSIDIAN_VAULT")
    if env_val is not None:
        if env_val.strip().lower() in ("", "none"):
            return VaultInfo("none", None, "GLOSA_OBSIDIAN_VAULT explicitly empty/none")
        p = Path(os.path.expanduser(env_val)).resolve()
        if p.is_dir():
            return VaultInfo("env", p, f"GLOSA_OBSIDIAN_VAULT={p}")
        return VaultInfo("none", None, f"GLOSA_OBSIDIAN_VAULT={env_val} does not exist — no vault, bridge skipped")

    profile_vault = _author_profile_vault()
    if profile_vault is not None:
        if profile_vault.is_dir():
            return VaultInfo("profile", profile_vault.resolve(),
                              f"author_profile.json defaults.obsidian_vault={profile_vault}")
        return VaultInfo("none", None,
                          f"author_profile.json names {profile_vault} but it does not exist — bridge skipped")

    # self mode: the glosa repo itself, opened as a vault at <repo>/obsidian/
    self_path = (REPO_ROOT / "obsidian").resolve()
    return VaultInfo("self", self_path, "no env/profile vault configured — using glosa repo itself as the vault "
                                          "(self mode; open the glosa repo root in Obsidian)")


def cmd_detect(args: argparse.Namespace) -> int:
    info = detect()
    print(f"glosa obsidian_bridge v{VERSION} (yaml backend: {_YAML_BACKEND})")
    if info.mode == "none":
        print("no vault — bridge skipped")
        print(f"  reason: {info.reason}")
        return 0
    print(f"vault mode: {info.mode}")
    print(f"vault path: {info.path}")
    print(f"reason: {info.reason}")
    has_dot_obsidian = (info.path / ".obsidian").is_dir() if info.path else False
    print(f".obsidian present at vault root: {has_dot_obsidian}")
    return 0


# --------------------------------------------------------------------------
# Generic helpers
# --------------------------------------------------------------------------
def slugify(s: str) -> str:
    s = re.sub(r"[^\w\-\. ]+", "", s, flags=re.UNICODE).strip()
    s = re.sub(r"\s+", "_", s)
    return s or "untitled"


def wikilink(title: str) -> str:
    return f"[[{title}]]"


def header(source_rel: str) -> str:
    return GENERATED_HEADER.format(version=VERSION, source=source_rel)


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def frontmatter(fields: dict[str, Any]) -> str:
    lines = ["---"]
    for k, v in fields.items():
        if isinstance(v, list):
            if not v:
                lines.append(f"{k}: []")
            else:
                lines.append(f"{k}:")
                for item in v:
                    lines.append(f"  - {_fm_scalar(item)}")
        else:
            lines.append(f"{k}: {_fm_scalar(v)}")
    lines.append("---")
    return "\n".join(lines) + "\n"


def _fm_scalar(v: Any) -> str:
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    s = str(v)
    if any(c in s for c in [":", "#", "\n"]) or s.strip() != s:
        return json.dumps(s, ensure_ascii=False)
    return s


class GeneratedFile:
    __slots__ = ("rel_path", "content")

    def __init__(self, rel_path: str, content: str):
        self.rel_path = rel_path
        self.content = content


# --------------------------------------------------------------------------
# Source scanning (reads REPO_ROOT, never the vault)
# --------------------------------------------------------------------------
def _dget(d: Any, *path, default=None):
    cur = d
    for p in path:
        if not isinstance(cur, dict):
            return default
        cur = cur.get(p, default)
        if cur is None:
            return default
    return cur


def scan_claim_cards() -> list[dict]:
    out = []
    for base in (REPO_ROOT / "paper" / "claims", REPO_ROOT / "cases"):
        if not base.is_dir():
            continue
        for f in sorted(base.glob("*.yaml")):
            data = load_yaml_file(f)
            card = data.get("claim_card") if isinstance(data, dict) else None
            if not isinstance(card, dict):
                continue
            card["_source_path"] = str(f.relative_to(REPO_ROOT))
            out.append(card)
    return out


def scan_blackbox_notes() -> list[dict]:
    out = []
    base = REPO_ROOT / "blackbox"
    if not base.is_dir():
        return out
    for f in sorted(base.iterdir()):
        if f.name in ("README.md",) or f.is_dir():
            continue
        rel = str(f.relative_to(REPO_ROOT))
        if f.suffix in (".yaml", ".yml"):
            data = load_yaml_file(f)
            note = data.get("blackbox_note") if isinstance(data, dict) else data
            if isinstance(note, dict):
                note["_source_path"] = rel
                note["_kind"] = "yaml"
                out.append(note)
        elif f.suffix == ".md":
            out.append({"_source_path": rel, "_kind": "md", "id": f.stem})
    return out


def scan_kg() -> tuple[list[dict], list[dict]]:
    nodes, edges = [], []
    kg_dir = REPO_ROOT / "kg"
    node_file = kg_dir / "nodes.jsonl"
    edge_file = kg_dir / "edges.jsonl"
    if node_file.is_file():
        for line in node_file.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                nodes.append(json.loads(line))
            except Exception:
                continue
    if edge_file.is_file():
        for line in edge_file.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                edges.append(json.loads(line))
            except Exception:
                continue
    return nodes, edges


def scan_records_lit(root: Path | None = None) -> dict[str, dict]:
    """records/lit/<hypothesis_slug>/ -> {slug: {search_log, citations[], dialogue_table_path,
    litreview_manifest, acquisitions[]}}. Detection is by shape, not fixed filenames, so this
    tolerates whatever real layout the literature-review agent lands on."""
    base = (root or REPO_ROOT) / "records" / "lit"
    result: dict[str, dict] = {}
    if not base.is_dir():
        return result
    for hyp_dir in sorted(p for p in base.iterdir() if p.is_dir()):
        slug = hyp_dir.name
        entry = {
            "dir": hyp_dir, "search_log": None, "citations": [], "acquisitions": [],
            "dialogue_table_path": None, "litreview_manifest": None,
        }
        for f in sorted(hyp_dir.rglob("*")):
            if f.is_dir():
                continue
            if f.suffix == ".md" and "dialogue" in f.name.lower():
                entry["dialogue_table_path"] = f
                continue
            if f.suffix not in (".yaml", ".yml"):
                continue
            data = load_yaml_file(f)
            if not isinstance(data, dict):
                continue
            if "search_mode" in data:
                entry["search_log"] = (f, data)
            elif "identifier" in data and "fetch_status" in data:
                entry["citations"].append((f, data))
            elif "acquisition_route" in data or "acquisition_status" in data:
                entry["acquisitions"].append((f, data))
            elif "gate" in data and "strata_table" in data:
                entry["litreview_manifest"] = (f, data)
        result[slug] = entry
    return result


def scan_hypothesis_selections(root: Path | None = None) -> list[tuple[Path, dict]]:
    out = []
    base = (root or REPO_ROOT) / "records" / "lit"
    if not base.is_dir():
        return out
    for f in base.glob("*.yaml"):
        data = load_yaml_file(f)
        if isinstance(data, dict) and "candidates" in data and "selection" in data:
            out.append((f, data))
    return out


# --------------------------------------------------------------------------
# Note builders
# --------------------------------------------------------------------------
def build_claim_note(card: dict) -> GeneratedFile:
    claim_id = card.get("claim_id") or "UNKNOWN-CLAIM"
    source = card.get("_source_path", "")
    fm = {
        "id": claim_id,
        "tier": card.get("tier"),
        "k_state": card.get("k_state"),
        "spine_stage": card.get("status"),
        "genre": card.get("genre"),
        "produced_by": card.get("produced_by"),
    }
    body = [header(source), "", f"# {claim_id}", ""]
    stmt = _dget(card, "statement", "text")
    if stmt:
        body += ["## Statement", "", str(stmt), ""]
    en = _dget(card, "statement", "translation", "text")
    if en:
        body += ["## Translation", "", str(en), ""]
    five_q_falsifier = _dget(card, "five_questions", "tested", "falsifier")
    if five_q_falsifier:
        body += ["## Five questions — falsifier (Q5)", "", str(five_q_falsifier), ""]
    origin = card.get("origin_blackbox_ref")
    body.append("## Links")
    body.append("")
    if origin:
        bb_id = Path(str(origin).split("#")[0]).stem
        body.append(f"- origin: {wikilink(bb_id)} (`{origin}`)")
    for rel_key, label in (
        ("related_citation_cards", "citation"),
        ("related_source_cards", "source"),
        ("related_observation_cards", "observation"),
    ):
        for ref in card.get(rel_key) or []:
            body.append(f"- {label}: {wikilink(str(ref))}")
    lens_ref = _dget(card, "lens_translation", "lens_ref")
    if lens_ref:
        body.append(f"- lens: {wikilink(LENS_NOTE_TITLE)}")
    body.append("")
    body.append(f"Source of record: `{source}` — this note is a readout, edit the source there.")
    return GeneratedFile(f"claims/{claim_id}.md", frontmatter(fm) + "\n" + "\n".join(body) + "\n")


def build_blackbox_note(note: dict) -> GeneratedFile:
    source = note.get("_source_path", "")
    note_id = note.get("id") or Path(source).stem
    fm = {"id": note_id, "kind": note.get("_kind", "unknown")}
    body = [header(source), "", f"# Blackbox Note {note_id}", ""]
    lens = note.get("lens_used") if isinstance(note.get("lens_used"), dict) else None
    if lens:
        body += ["## Lens used", "", f"- {wikilink(LENS_NOTE_TITLE)}", f"- display: {lens.get('display', '')}", ""]
    lines = note.get("lines")
    if isinstance(lines, list):
        body.append("## Lines (index only — full verbatim text stays in the source file)")
        body.append("")
        for ln in lines:
            if not isinstance(ln, dict):
                continue
            n = ln.get("n")
            speaker = ln.get("speaker")
            kind = ln.get("kind")
            public = ln.get("public")
            body.append(f"- line {n} — {speaker} ({kind}) — public: {public}")
        body.append("")
    body.append(f"Source of record: `{source}`.")
    return GeneratedFile(f"blackbox/{slugify(note_id)}.md", frontmatter(fm) + "\n" + "\n".join(body) + "\n")


def build_kg_note(node: dict, edges: list[dict]) -> GeneratedFile:
    node_id = node.get("id") or "UNKNOWN-NODE"
    fm = {"id": node_id, "type": node.get("type"), "tier": node.get("tier"), "status": node.get("status")}
    body = [header("kg/nodes.jsonl (+ kg/edges.jsonl)"), "", f"# {node.get('label') or node_id}", ""]
    ref = node.get("ref")
    if ref:
        body.append(f"- canonical source: `{ref}`")
    body.append("")
    body.append("## Edges")
    body.append("")
    for e in edges:
        if e.get("from") == node_id:
            body.append(f"- {e.get('relation')} → {wikilink(e.get('to', ''))} (status: {e.get('status')})")
        elif e.get("to") == node_id:
            body.append(f"- ← {e.get('relation')} {wikilink(e.get('from', ''))} (status: {e.get('status')})")
    body.append("")
    return GeneratedFile(f"kg/{slugify(node_id)}.md", frontmatter(fm) + "\n" + "\n".join(body) + "\n")


def build_lens_stub_note() -> GeneratedFile:
    fm = {"id": "lens-readout-universe", "role": "external_lens_reference"}
    body = [
        header("(no single source file — a standing citation, see design/FOUNDATION_v0.5.md §2.3)"),
        "",
        f"# {LENS_NOTE_TITLE}",
        "",
        "readout-not-truth; retained distinction; Readout Condition E-A-D "
        "(Readout Universe / Readout Genesis).",
        "",
        "- https://github.com/morrocwi/readout_universe",
        "- https://github.com/morrocwi/readout_genesis",
        "",
        "Any claim/blackbox note in this vault linking here is crediting the lens as its source; "
        "this does not raise that claim's tier or independence class ('attribution ≠ authority').",
    ]
    return GeneratedFile(f"{LENS_NOTE_TITLE}.md", frontmatter(fm) + "\n" + "\n".join(body) + "\n")


def build_hypothesis_note(slug: str, entry: dict) -> GeneratedFile:
    fm = {"id": slug}
    body = [header(f"records/lit/{slug}/"), "", f"# Hypothesis: {slug}", ""]
    sl = entry.get("search_log")
    if sl:
        f, data = sl
        body.append(f"- search_log: `{f.relative_to(REPO_ROOT)}` (mode: {data.get('search_mode')})")
    lm = entry.get("litreview_manifest")
    if lm:
        f, data = lm
        gate = data.get("gate") or {}
        body.append(f"- litreview_manifest: `{f.relative_to(REPO_ROOT)}` "
                     f"(accuracy_gate: {gate.get('accuracy_gate')}, diversity_gate: {gate.get('diversity_gate')}, "
                     f"overall: {gate.get('overall')})")
    dt = entry.get("dialogue_table_path")
    if dt:
        body.append(f"- dialogue_table: `{dt.relative_to(REPO_ROOT)}`")
    body.append("")
    body.append("## Sources")
    body.append("")
    for f, cdata in entry.get("citations", []):
        cid = cdata.get("id") or f.stem
        body.append(f"- {wikilink(cid)}")
    body.append("")
    body.append("Backlinks (agree/disagree clusters, orphans, concentration) show up in Obsidian's "
                 "own graph/backlink panel once source notes below link here and to each other — "
                 "this bridge only writes the links, Obsidian renders the graph.")
    return GeneratedFile(f"records_lit/{slugify(slug)}/00_hypothesis.md",
                          frontmatter(fm) + "\n" + "\n".join(body) + "\n")


def build_source_note(slug: str, hyp_slug: str, cdata: dict, source_rel: str,
                       all_citations: list[dict]) -> GeneratedFile:
    cid = cdata.get("id") or slug
    dialogue_stance = None  # filled in by caller if a dialogue_table row is matched; kept generic here
    fm = {
        "source_id": cid,
        "stance": cdata.get("_stance", "undetermined"),
        "region": _dget(cdata, "_diversity", "geography_or_institution") or "",
        "language": _dget(cdata, "_diversity", "language") or "",
        "source_type": _dget(cdata, "_diversity", "source_type") or "",
        "venue_quality_index": _dget(cdata, "_diversity", "venue_quality_index", "value"),
        "verified": bool(cdata.get("status") == "VERIFIED"),
    }
    body = [header(source_rel), "", f"# {cid}", ""]
    body.append(f"- hypothesis: {wikilink(hyp_slug)}")
    ident = cdata.get("identifier") or {}
    if ident:
        body.append(f"- identifier: {ident.get('kind')} {ident.get('value')}")
    body.append(f"- fetch_status: {cdata.get('fetch_status')}")
    body.append(f"- status: {cdata.get('status')}")
    stance = fm["stance"]
    for other in all_citations:
        other_id = other.get("id")
        if not other_id or other_id == cid:
            continue
        other_stance = other.get("_stance")
        if other_stance and other_stance == stance and stance in ("agree", "disagree"):
            body.append(f"- {stance}s-with-cluster: {wikilink(other_id)}")
    body.append("")
    return GeneratedFile(f"records_lit/{slugify(hyp_slug)}/sources/{slugify(cid)}.md",
                          frontmatter(fm) + "\n" + "\n".join(body) + "\n")


def build_hypothesis_selection_note(f: Path, data: dict) -> GeneratedFile:
    hid = data.get("id") or f.stem
    fm = {"id": hid, "decided_by": data.get("decided_by"), "decided_at": data.get("decided_at")}
    body = [header(str(f.relative_to(REPO_ROOT))), "", f"# Hypothesis selection {hid}", ""]
    sel = data.get("selection") or {}
    chosen = sel.get("chosen") or []
    body.append("## Chosen")
    body.append("")
    for c in chosen:
        body.append(f"- {wikilink(str(c))}")
    body.append("")
    body.append("## Parked")
    body.append("")
    for p in sel.get("parked") or []:
        if isinstance(p, dict):
            body.append(f"- {wikilink(str(p.get('hypothesis_ref')))} — {p.get('reason', '')}")
    body.append("")
    return GeneratedFile("records_lit/00_hypothesis_selection.md",
                          frontmatter(fm) + "\n" + "\n".join(body) + "\n")


# --------------------------------------------------------------------------
# Index
# --------------------------------------------------------------------------
def build_index(claims: list[dict], blackbox: list[dict], nodes: list[dict],
                 lit: dict, hyp_selections: list, vault: VaultInfo) -> GeneratedFile:
    body = [header("(index — aggregates the whole glosa repo readout)"), "",
            "# glosa — Obsidian bridge index", "",
            f"vault mode: `{vault.mode}` — {vault.reason}", ""]

    body.append("## Research library / registry")
    body.append("")
    if (REPO_ROOT / "RESEARCH_LIBRARY.md").is_file():
        body.append("- `RESEARCH_LIBRARY.md` (rendered from `registry/RESEARCH_REGISTRY.yaml`)")
    else:
        body.append("- no `RESEARCH_LIBRARY.md` yet — registry not built at bridge-run time.")
    body.append("")

    body.append("## Claim cards")
    body.append("")
    if claims:
        for c in claims:
            body.append(f"- {wikilink(c.get('claim_id', 'UNKNOWN'))} — {c.get('tier')}/{c.get('k_state')}")
    else:
        body.append("- none found under `paper/claims/` or `cases/` at bridge-run time.")
    body.append("")

    body.append("## Blackbox notes")
    body.append("")
    if blackbox:
        for n in blackbox:
            nid = n.get("id") or Path(n.get("_source_path", "?")).stem
            body.append(f"- {wikilink(nid)}")
    else:
        body.append("- none found under `blackbox/`.")
    body.append("")

    body.append("## Knowledge graph")
    body.append("")
    if nodes:
        for n in nodes:
            body.append(f"- {wikilink(n.get('id', '?'))} ({n.get('type')})")
    else:
        body.append("- `kg/nodes.jsonl` absent or empty at bridge-run time.")
    body.append("")

    body.append("## Literature review (per hypothesis)")
    body.append("")
    if lit:
        for slug in sorted(lit):
            body.append(f"- {wikilink(slug)}")
    else:
        body.append("- no `records/lit/<hypothesis>/` folders yet.")
    body.append("")

    if hyp_selections:
        body.append(f"## Hypothesis selection")
        body.append("")
        body.append(f"- {wikilink('00_hypothesis_selection')}")
        body.append("")

    body.append("## Incidents")
    body.append("")
    inc_dir = REPO_ROOT / "incidents"
    if inc_dir.is_dir():
        for f in sorted(inc_dir.glob("*.md")):
            if f.name == "README.md":
                continue
            body.append(f"- `{f.relative_to(REPO_ROOT)}`")
    body.append("")

    body.append("## Methodology cards")
    body.append("")
    meth_dir = REPO_ROOT / "methodology"
    if meth_dir.is_dir():
        for f in sorted(meth_dir.glob("P*.md")):
            body.append(f"- `{f.relative_to(REPO_ROOT)}`")
    body.append("")

    body.append("## Lens")
    body.append("")
    body.append(f"- {wikilink(LENS_NOTE_TITLE)}")
    body.append("")
    body.append("_Obsidian is an analysis surface for this repo's own files — the graph and "
                "backlinks help a human SEE clusters (agree/disagree, concentration, orphans); it "
                "is never the source of truth. The source of truth is always the file named in "
                "each note's header._")

    return GeneratedFile("00_INDEX.md", "\n".join(body) + "\n")


# --------------------------------------------------------------------------
# Manifest + write helpers
# --------------------------------------------------------------------------
def load_manifest(vault_glosa_dir: Path) -> dict:
    mf = vault_glosa_dir / MANIFEST_NAME
    if mf.is_file():
        try:
            return json.loads(mf.read_text(encoding="utf-8"))
        except Exception:
            return {"version": VERSION, "files": {}}
    return {"version": VERSION, "files": {}}


def save_manifest(vault_glosa_dir: Path, manifest: dict) -> None:
    mf = vault_glosa_dir / MANIFEST_NAME
    mf.write_text(json.dumps(manifest, indent=2, ensure_ascii=False, sort_keys=True) + "\n", encoding="utf-8")


def write_generated(vault_glosa_dir: Path, files: list[GeneratedFile], dry_run: bool) -> dict:
    manifest = load_manifest(vault_glosa_dir)
    new_files: dict[str, str] = {}
    written, unchanged = 0, 0
    for gf in files:
        dest = vault_glosa_dir / gf.rel_path
        digest = sha256_text(gf.content)
        new_files[gf.rel_path] = digest
        if dry_run:
            print(f"  [dry-run] would write {dest} ({'new' if gf.rel_path not in manifest.get('files', {}) else 'refresh'})")
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        old = dest.read_text(encoding="utf-8") if dest.is_file() else None
        if old == gf.content:
            unchanged += 1
            continue
        dest.write_text(gf.content, encoding="utf-8")
        written += 1

    stale = set(manifest.get("files", {})) - set(new_files)
    for rel in sorted(stale):
        target = vault_glosa_dir / rel
        if dry_run:
            print(f"  [dry-run] would remove stale generated note {target}")
            continue
        if target.is_file() and "generated by glosa obsidian_bridge" in target.read_text(encoding="utf-8", errors="ignore"):
            target.unlink()

    if not dry_run:
        manifest["version"] = VERSION
        manifest["files"] = new_files
        save_manifest(vault_glosa_dir, manifest)

    print(f"sync: {written} written, {unchanged} unchanged, {len(stale)} stale removed"
          f"{' (dry-run, nothing actually written)' if dry_run else ''}")
    return manifest


# --------------------------------------------------------------------------
# sync
# --------------------------------------------------------------------------
def cmd_sync(args: argparse.Namespace) -> int:
    if args.vault:
        vault_path = Path(os.path.expanduser(args.vault)).resolve()
        info = VaultInfo("cli", vault_path, f"--vault {vault_path}")
    else:
        info = detect()

    if info.mode == "none" or info.path is None:
        print("no vault — bridge skipped")
        print(f"  reason: {info.reason}")
        return 0

    vault_glosa_dir = info.path / "glosa"
    if not args.dry_run:
        vault_glosa_dir.mkdir(parents=True, exist_ok=True)
    print(f"sync target: {vault_glosa_dir} (mode: {info.mode})")

    claims = scan_claim_cards()
    blackbox = scan_blackbox_notes()
    nodes, edges = scan_kg()
    lit = scan_records_lit()
    hyp_selections = scan_hypothesis_selections()

    files: list[GeneratedFile] = []
    files.append(build_index(claims, blackbox, nodes, lit, hyp_selections, info))
    for c in claims:
        files.append(build_claim_note(c))
    for n in blackbox:
        files.append(build_blackbox_note(n))
    for n in nodes:
        files.append(build_kg_note(n, edges))
    if claims or nodes or lit:
        files.append(build_lens_stub_note())

    for slug, entry in lit.items():
        files.append(build_hypothesis_note(slug, entry))
        cdatas = []
        for f, cdata in entry.get("citations", []):
            stance = None
            dt = entry.get("dialogue_table_path")
            if dt and dt.is_file():
                stance = _guess_stance_from_dialogue_table(dt.read_text(encoding="utf-8", errors="ignore"),
                                                             cdata.get("id", ""))
            cdata = dict(cdata)
            cdata["_stance"] = stance or "undetermined"
            cdatas.append(cdata)
        for (f, _orig), cdata in zip(entry.get("citations", []), cdatas):
            files.append(build_source_note(f.stem, slug, cdata, str(f.relative_to(REPO_ROOT)), cdatas))

    for f, data in hyp_selections:
        files.append(build_hypothesis_selection_note(f, data))

    write_generated(vault_glosa_dir, files, args.dry_run)
    return 0


def _guess_stance_from_dialogue_table(text: str, citation_id: str) -> str | None:
    if not citation_id:
        return None
    # Column-position heuristic against templates/knowledge/dialogue_table.md's fixed header:
    # | source | how it sees | what it separates | what it assumes | agrees with H | disagrees with H | ... | citation_card | verified |
    for line in text.splitlines():
        if "|" not in line or citation_id not in line:
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 8:
            continue
        agrees, disagrees = cells[4].upper(), cells[5].upper()
        if agrees == "YES":
            return "agree"
        if disagrees == "YES":
            return "disagree"
        if agrees == "ORTHOGONAL" or disagrees == "ORTHOGONAL":
            return "orthogonal"
    return None


# --------------------------------------------------------------------------
# check
# --------------------------------------------------------------------------
def cmd_check(args: argparse.Namespace) -> int:
    if args.vault:
        info = VaultInfo("cli", Path(os.path.expanduser(args.vault)).resolve(), f"--vault {args.vault}")
    else:
        info = detect()

    print(f"vault mode: {info.mode}")
    if info.mode == "none" or info.path is None:
        print("no vault — bridge skipped (nothing to check)")
        return 0

    vault_glosa_dir = info.path / "glosa"
    print(f"vault path: {info.path}")
    print(f"glosa subdir present: {vault_glosa_dir.is_dir()}")
    if not vault_glosa_dir.is_dir():
        return 0

    manifest = load_manifest(vault_glosa_dir)
    files = manifest.get("files", {})
    print(f"generated files tracked in manifest: {len(files)}")

    all_titles = set()
    for rel in files:
        all_titles.add(Path(rel).stem)

    dangling = []
    link_re = re.compile(r"\[\[([^\]|#]+)")
    for rel in files:
        p = vault_glosa_dir / rel
        if not p.is_file():
            continue
        for m in link_re.finditer(p.read_text(encoding="utf-8", errors="ignore")):
            target = m.group(1).strip()
            if target not in all_titles:
                dangling.append((rel, target))

    print(f"dangling wikilinks: {len(dangling)}")
    for rel, target in dangling[:50]:
        print(f"  [DANGLING] {rel} -> [[{target}]]")
    return 0


# --------------------------------------------------------------------------
# harvest
# --------------------------------------------------------------------------
TAG_RE = re.compile(r"#([A-Za-z0-9_/\-]+)")


def cmd_harvest(args: argparse.Namespace) -> int:
    if args.vault:
        info = VaultInfo("cli", Path(os.path.expanduser(args.vault)).resolve(), f"--vault {args.vault}")
    else:
        info = detect()
    if info.mode == "none" or info.path is None:
        print("no vault — bridge skipped")
        return 0

    vault_glosa_dir = info.path / "glosa"
    lit_dir = vault_glosa_dir / "records_lit"
    if not lit_dir.is_dir():
        print("no records_lit/ notes under this vault — nothing to harvest")
        return 0

    manifest = load_manifest(vault_glosa_dir)
    known_files = set(manifest.get("files", {}))

    harvested_by_hyp: dict[str, list[dict]] = {}
    for src_note in lit_dir.glob("*/sources/*.md"):
        rel = str(src_note.relative_to(vault_glosa_dir))
        text = src_note.read_text(encoding="utf-8", errors="ignore")
        header_marker = "generated by glosa obsidian_bridge"
        # split off the generated header block; anything a human appended after it (or a tag
        # anywhere in the body) is a harvest candidate — we never assume the header lines are
        # human content.
        body_after_header = text.split(header_marker, 1)[-1]
        tags = sorted(set(TAG_RE.findall(body_after_header)))
        if not tags:
            continue
        hyp_slug = src_note.parent.parent.name
        source_id = src_note.stem
        harvested_by_hyp.setdefault(hyp_slug, []).append({
            "source_id": source_id,
            "note_path": rel,
            "tags_found": tags,
            "candidate_edits": _tags_to_candidate_edits(tags),
        })

    if not harvested_by_hyp:
        print("no human-added tags found in generated source notes — nothing to harvest")
        return 0

    for hyp_slug, rows in harvested_by_hyp.items():
        out_dir = REPO_ROOT / "records" / "lit" / hyp_slug
        out_path = out_dir / "obsidian_harvest.yaml"
        content = _render_harvest_yaml(hyp_slug, rows)
        if args.dry_run:
            print(f"[dry-run] would write {out_path}:")
            print(content)
            continue
        out_dir.mkdir(parents=True, exist_ok=True)
        out_path.write_text(content, encoding="utf-8")
        print(f"wrote candidate edits: {out_path} ({len(rows)} source(s) with tags)")

    print("These are CANDIDATE edits only — no source YAML was modified. "
          "A human must review obsidian_harvest.yaml and apply confirmed edits by hand.")
    return 0


def _tags_to_candidate_edits(tags: list[str]) -> list[dict]:
    edits = []
    for t in tags:
        if t.startswith("disagrees_"):
            edits.append({"field": "dialogue_table_stance", "candidate_value": "disagrees",
                          "note": f"from tag #{t}"})
        elif t.startswith("agrees_"):
            edits.append({"field": "dialogue_table_stance", "candidate_value": "agrees",
                          "note": f"from tag #{t}"})
        elif t.startswith("region/"):
            edits.append({"field": "diversity.geography_or_institution", "candidate_value": t.split("/", 1)[1],
                          "note": f"from tag #{t}"})
        elif t.startswith("language/") or t.startswith("lang/"):
            edits.append({"field": "diversity.language", "candidate_value": t.split("/", 1)[1],
                          "note": f"from tag #{t}"})
        else:
            edits.append({"field": None, "candidate_value": None, "note": f"unrecognized tag #{t} — human judgement needed"})
    return edits


def _render_harvest_yaml(hyp_slug: str, rows: list[dict]) -> str:
    lines = [
        f"# obsidian_harvest.yaml — CANDIDATE edits harvested from human tags in Obsidian,",
        f"# generated by tools/obsidian_bridge.py harvest for hypothesis '{hyp_slug}'.",
        "# These are proposals only. A human confirms and applies them by hand to the real",
        "# citation_card.yaml / dialogue_table.md — this file never gets auto-applied.",
        f"hypothesis: {hyp_slug}",
        "harvested_at_tool_version: " + VERSION,
        "sources:",
    ]
    for row in rows:
        lines.append(f"  - source_id: {row['source_id']}")
        lines.append(f"    note_path: {row['note_path']}")
        lines.append(f"    tags_found: {json.dumps(row['tags_found'], ensure_ascii=False)}")
        lines.append("    candidate_edits:")
        for e in row["candidate_edits"]:
            lines.append(f"      - field: {e['field']}")
            lines.append(f"        candidate_value: {json.dumps(e['candidate_value'], ensure_ascii=False)}")
            lines.append(f"        note: {json.dumps(e['note'], ensure_ascii=False)}")
        lines.append("    confirmed: false   # human sets true after manually applying to the source file")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------
# unlink
# --------------------------------------------------------------------------
def cmd_unlink(args: argparse.Namespace) -> int:
    if args.vault:
        info = VaultInfo("cli", Path(os.path.expanduser(args.vault)).resolve(), f"--vault {args.vault}")
    else:
        info = detect()
    if info.mode == "none" or info.path is None:
        print("no vault — bridge skipped")
        return 0

    vault_glosa_dir = info.path / "glosa"
    if not vault_glosa_dir.is_dir():
        print("nothing to unlink — no glosa/ subdir in this vault")
        return 0

    manifest = load_manifest(vault_glosa_dir)
    files = manifest.get("files", {})
    removed = 0
    for rel in sorted(files):
        p = vault_glosa_dir / rel
        if p.is_file() and "generated by glosa obsidian_bridge" in p.read_text(encoding="utf-8", errors="ignore"):
            p.unlink()
            removed += 1
    # prune now-empty directories
    for d in sorted(vault_glosa_dir.rglob("*"), key=lambda p: -len(str(p))):
        if d.is_dir():
            try:
                d.rmdir()
            except OSError:
                pass
    mf = vault_glosa_dir / MANIFEST_NAME
    if mf.is_file():
        mf.unlink()
    print(f"unlink: removed {removed} bridge-generated file(s) from {vault_glosa_dir}")
    return 0


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------
def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="obsidian_bridge.py", description=__doc__.splitlines()[1])
    sub = parser.add_subparsers(dest="cmd", required=True)

    sub.add_parser("detect", help="report which vault (if any) would be used")

    p_sync = sub.add_parser("sync", help="create/refresh <vault>/glosa/ from the repo's own files")
    p_sync.add_argument("--vault", default=None, help="override vault path (skips detect())")
    p_sync.add_argument("--dry-run", action="store_true", help="report what would change, write nothing")

    p_check = sub.add_parser("check", help="report vault presence, counts, dangling links")
    p_check.add_argument("--vault", default=None)

    p_harvest = sub.add_parser("harvest", help="read human-added tags back as candidate edits")
    p_harvest.add_argument("--vault", default=None)
    p_harvest.add_argument("--dry-run", action="store_true")

    p_unlink = sub.add_parser("unlink", help="remove only bridge-generated files, tracked via manifest")
    p_unlink.add_argument("--vault", default=None)

    args = parser.parse_args(argv)
    return {
        "detect": cmd_detect,
        "sync": cmd_sync,
        "check": cmd_check,
        "harvest": cmd_harvest,
        "unlink": cmd_unlink,
    }[args.cmd](args)


if __name__ == "__main__":
    sys.exit(main())
